name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macOS-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v7.0.1
    - name: SPM tests
      run: swift test --enable-code-coverage --parallel
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/compress-nioPackageTests.xctest/Contents/MacOs/compress-nioPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:6.2'
          - 'swift:6.3'
          - 'swift:6.4'
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test --enable-code-coverage --parallel
    - name: Upload coverage data
      uses: vapor/swift-codecov-action@c93caea6600dbe3af0266a8ef6ee195c00181f04  # v0.3.7
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}