name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macOS-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v4
    - name: SPM tests
      run: swift test --enable-code-coverage --parallel
    - name: Convert coverage files
      run: |
        xcrun llvm-cov export -format "lcov" \
          .build/debug/compress-nioPackageTests.xctest/Contents/MacOs/compress-nioPackageTests \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile=.build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'swift:5.9'
          - 'swift:5.10'
          - 'swift:6.0'
    container:
      image: ${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift --version
        swift test --enable-code-coverage --parallel
    - name: Convert coverage files
      run: |
        llvm-cov export -format="lcov" \
          .build/debug/compress-nioPackageTests.xctest \
          -ignore-filename-regex="\/Tests\/" \
          -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        file: info.lcov
